### PR TITLE
Use named folder so it can retrieve its version

### PR DESCRIPTION
**Pull request by flying-sheep**
Currently, get_version installed by conda reports its own version as 0.0.0. I’m pretty sure that’s because it doesn’t leave the files inside of the directory from the .tar.gz (`get_version-2.1`), as discovered in flying-sheep/get_version#6.

* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Whoops, didn’t know about the fork thing. Ugh, not a fan of having a fork of something I can push to, but next time…

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by flying-sheep** [comment]
@grst source.folder doesn’t seem to work. Can you help?

**Comment by grst** [comment]
Another option would be to retrieve the package from PyPI instead of GitHub. Then the version should be included. 

I just remember that I initially tried that and it failed with a weird encoding error message on Windows...

**Comment by grst** [comment]
getting there... (slowly)

**Comment by flying-sheep** [comment]
Not that slowly, seems to have done the trick!

**Pull request merged**
